#!/usr/bin/env bash

# ============================================================================================ #
#: Title           : HistLog                                                                   #
#: Sypnosis        : HistLog                                                                   #
#: Date Created    : Sun Jul 27 18:07:40 PHT 2014 / Sun Jul 27 10:08:00 UTC 2014               #
#: Last Edit       : Sun Feb  8 12:12:52 PHT 2015 / Sun Feb  8 04:12:52 UTC 2015               #
#: License         : GPLv3                                                                     #
#: Version         : 3.2.10                                                                    #
#: Author          : Jason V. Ferrer '<jetchisel@opensuse.org>'                                #
#: Description     : Logs ~/.bash_history to ~/.bash_history.archive  after 10000 lines.       #
#: Options         : NONE                                                                      #
#: Home Page       : NONE                                                                      #
#: ExtComm         : ed,crontab,grep,wc                                                        #
# ============================================================================================ #

# ******************************************************************************************** #
#                                                                                              #
#   Warn and die functions, for exit messages and default status or an optional exit status.   #
#                                                                                              #
# ******************************************************************************************** #

warn() {
  printf '%s\n' "${BASH_SOURCE##*/}: error: $*" >&2
}

die() {
  local st=$?
  case $2 in
    *[^0-9]*|'') :;;
    *) st=$2;;
  esac
  warn "$1"
  exit "$st"
}

# ******************************************************************************************** #
#                                                                                              #
#    Log everything to the desired log file. (NOTE: Builtins only on this part to be safe)     #
#                                                                                              #
# ******************************************************************************************** #

Date=$(printf "%(%h %d %Y %H:%M:%S)T" -1)
Log=$HOME/.HistLog

exec > >(
  while read -r; do
    printf '[%s] %s\n' "$Date" "$REPLY" >> "$Log"
  done
) 2>&1

# ******************************************************************************************** #
#                                                                                              #
#     Set the PATH just to be safe and cron will not complain about "command not found".       #
#                                                                                              #
# ******************************************************************************************** #

PATH=/usr/local/bin:/usr/bin:/bin
export PATH

# ******************************************************************************************** #
#                                                                                              #
#          Check for the required app/executable is with in your PATH, exit otherwise.         #
#                                                                                              #
# ******************************************************************************************** #

Missing=()
ExtComm=(ed crontab grep wc)
ExitMessage="Please install the following: "
MissingMessage="is either not installed or it is not in your PATH!"

for apps in "${ExtComm[@]}"; do
  if ! type -P "$apps" >/dev/null; then
    printf '%s %s\n' "$apps" "$MissingMessage" >&2
    Missing+=("$apps")
  fi
done

(( ${#Missing[@]} )) && die "$ExitMessage[${Missing[*]}] exiting now!" 127

# ******************************************************************************************** #
#                                                                                              #
#       Put the crontab entry in an array.  (to run every 30 seconds adjust if needed.)        #
#                                                                                              #
# ******************************************************************************************** #

ArrayCrontabEntry=(
  "* * * * * $BASH_SOURCE"
  "* * * * * sleep 30; $BASH_SOURCE"
)

printf -v CronTabEntry '%s\n' "${ArrayCrontabEntry[@]}"
CronTabEntry=${CronTabEntry%$'\n'}

# ******************************************************************************************** #
#                                                                                              #
#      Make ed the default editor so "crontab -e" will accept ed syntax via a heredoc.         #
#                                                                                              #
# ******************************************************************************************** #

EDITOR=ed
export EDITOR

# ******************************************************************************************** #
#                                                                                              #
#                 Function to create an entry in cron using ed and a heredoc.                  #
#                                                                                              #
# ******************************************************************************************** #

CreateEntry() {
crontab -e << EOF
a
$CronTabEntry
.
w
q
EOF
}

# ******************************************************************************************** #
#                                                                                              #
#                           Add cron entry *ONLY* if there is none.                            #
#                                                                                              #
# ******************************************************************************************** #

if ! grep -q "$BASH_SOURCE" < <(crontab -l 2>/dev/null); then
  CreateEntry
fi

# ******************************************************************************************** #
#                                                                                              #
#         Assign/define bash_history and bash_history.archive log file in a variable.          #
#                                                                                              #
# ******************************************************************************************** #

History=${HOME}/.bash_history
Archive=${HOME}/.bash_history.archive

# ******************************************************************************************** #
#                                                                                              #
#  If bash_history.archive does not exists silently create it, otherwise exit with an error.   #
#                                                                                              #
# ******************************************************************************************** #

if [[ ! -f $Archive ]]; then
  printf '%s\n' "Creating ${Archive}..."
  > "$Archive" || die "Could not create ${Archive}!"
  printf '%s\n' "$Archive created succesfully."
fi

# ******************************************************************************************** #
#                                                                                              #
#  lines to cut from history and lines to be pasted in archive. (Adjust the value if needed).  #
#                                                                                              #
# ******************************************************************************************** #

CutLines=1,5000
PasteLines=5001,\$

# ******************************************************************************************** #
#                                                                                              #
# Function to Cut from 1 down 5000 lines from .bash_history and paste to .bash_history.archive.#
#                                                                                              #
# ******************************************************************************************** #

CutAndPaste() {
ed -s "$History" <<EOF
${CutLines}d
w
u
${PasteLines}d
r $Archive
${CutLines}m\$
w $Archive
EOF
}

# ******************************************************************************************** #
#                                                                                              #
#   Total lines of bash_history LogFile and the Maximum lines allowed before cut and paste.    #
#                                                                                              #
# ******************************************************************************************** #

History_Lines=$(wc -l < "$History")
MaxLines=10000

# ******************************************************************************************** #
#                                                                                              #
#      Some fancy output in a variable, will be printed when MaxLines has been reached.        #
#                                                                                              #
# ******************************************************************************************** #

length=14
printf -v line '%*s' "$length"

# ******************************************************************************************** #
#                                                                                              #
#  If Total_lines is more than 10000, move 5,000 to Archive and delete from from SourceFile.   #
#                                                                                              #
# ******************************************************************************************** #

if (( History_Lines > MaxLines )); then
  printf "%s\n" "${line// /=}>>> $History_Lines lines in $History Detected! <<<${line// /=}"
  printf '%s\n' "$History Current number of lines: $(wc -l < "$History")"
  printf '%s\n' "$Archive Current number of lines: $(wc -l < "$Archive")"
  printf '%s\n' "History is now $History_Lines lines, moving ${CutLines#*,} lines to $Archive"
  CutAndPaste
  printf '%s\n' "$History After removing ${CutLines#*,} lines: $(wc -l < "$History")"
  printf '%s\n' "$Archive After adding ${CutLines#*,} lines: $(wc -l < "$Archive")"
else
  printf '%s\n' "Your history is only [$(wc -l < "$History")] lines. Keep it comming!"
fi

# ******************************************************************************************** #
#                                                                                              #
#                                    Set the exit status.                                      #
#                                                                                              #
# ******************************************************************************************** #

exit 0

# ============================================================================================ #
#                                                                                              #
#                                    >>> END OF SCRIPT <<<                                     #
#                                                                                              #
# ============================================================================================ #
